'use client'

import { useState, useEffect } from 'react'
import { Sparkles, Copy, Check, RefreshCw } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import Button from '@/components/ui/Button'
import Card from '@/components/ui/Card'

interface Dog {
  id: string
  name: string
  breed: string | null
  age_years: number | null
  weight_lbs: number | null
  notes: string | null
  vet_name: string | null
  vet_phone: string | null
}

interface Routine {
  title: string
  category: string
  time_of_day: string | null
}

export default function SitterGuidePage() {
  const supabase = createClient()
  const [dog, setDog] = useState<Dog | null>(null)
  const [routines, setRoutines] = useState<Routine[]>([])
  const [guide, setGuide] = useState('')
  const [generating, setGenerating] = useState(false)
  const [copied, setCopied] = useState(false)
  const [savedGuide, setSavedGuide] = useState<string | null>(null)

  useEffect(() => { loadData() }, [])

  async function loadData() {
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const [{ data: dogs }, { data: rts }, { data: guides }] = await Promise.all([
      supabase.from('dogs').select('*').eq('owner_id', user.id).limit(1).single(),
      supabase.from('routines').select('title,category,time_of_day').eq('user_id', user.id).eq('active', true),
      supabase.from('sitter_guides').select('*').eq('user_id', user.id).order('created_at', { ascending: false }).limit(1),
    ])

    setDog(dogs ?? null)
    setRoutines(rts ?? [])
    if (guides && guides.length > 0) setSavedGuide(guides[0].content)
  }

  function generateGuideLocally(dog: Dog, routines: Routine[]): string {
    const name = dog.name
    const breed = dog.breed ?? 'mixed breed'
    const age = dog.age_years ? `${dog.age_years} year old` : ''
    const weight = dog.weight_lbs ? `, ${dog.weight_lbs} lbs` : ''
    const vet = dog.vet_name ? `\n- **Vet:** ${dog.vet_name}${dog.vet_phone ? ` — ${dog.vet_phone}` : ''}` : ''

    const byTime: Record<string, string[]> = {}
    routines.forEach(r => {
      const t = r.time_of_day ?? 'Anytime'
      if (!byTime[t]) byTime[t] = []
      byTime[t].push(r.title)
    })

    const schedule = Object.entries(byTime).map(([time, tasks]) =>
      `**${time}:**\n${tasks.map(t => `  - ${t}`).join('\n')}`
    ).join('\n\n')

    return `# Sitter Guide for ${name}

## About ${name}
${name} is a ${age} ${breed}${weight}. ${dog.notes ? `\n${dog.notes}` : ''}

## Emergency Info${vet}
- **Emergency vet:** nearest 24-hour animal hospital
- **Owner contact:** [your phone number]

## Daily Schedule
${schedule || 'No routines set up yet — check with the owner.'}

## Feeding
- Follow the feeding routine in the schedule above
- Fresh water available at all times
- Do not feed human food without owner approval

## Walks & Exercise
- Follow walking routines in the schedule
- Always use a leash
- Bring waste bags

## Important Notes
- ${name} may take a little time to warm up to new people — be patient and calm
- If any health concerns arise, contact the owner immediately
- Emergency vet number is listed above

---
*Generated by Four Leg Life — keep this guide handy!*`
  }

  async function generateGuide() {
    if (!dog) return
    setGenerating(true)

    const content = generateGuideLocally(dog, routines)
    setGuide(content)

    const { data: { user } } = await supabase.auth.getUser()
    if (user) {
      await supabase.from('sitter_guides').upsert({
        user_id: user.id,
        dog_id: dog.id,
        content,
        generated_at: new Date().toISOString(),
      }, { onConflict: 'user_id' })
      setSavedGuide(content)
    }
    setGenerating(false)
  }

  async function copyGuide() {
    const content = guide || savedGuide || ''
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const displayGuide = guide || savedGuide

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-charcoal-700">Sitter Guide</h1>
        {displayGuide && (
          <Button variant="secondary" size="sm" onClick={copyGuide}>
            {copied ? <><Check className="w-4 h-4" /> Copied!</> : <><Copy className="w-4 h-4" /> Copy</>}
          </Button>
        )}
      </div>

      <Card className="bg-gradient-to-br from-[#FFF9E6] to-[#FDF8F3] border border-[#E6D080]/30">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-2xl bg-[#FFF0C0] flex items-center justify-center flex-shrink-0">
            <Sparkles className="w-5 h-5 text-[#B8860B]" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-charcoal-700 mb-1">AI Sitter Guide Generator</h3>
            <p className="text-sm text-charcoal-500 mb-4">
              Generates a comprehensive care guide from your dog's profile and daily routines — ready to share with any sitter.
            </p>
            {!dog ? (
              <p className="text-sm text-[#E8705A]">Add a dog profile first to generate a guide.</p>
            ) : (
              <Button onClick={generateGuide} loading={generating}>
                {generating ? 'Generating...' : displayGuide ? <><RefreshCw className="w-4 h-4" /> Regenerate</> : <><Sparkles className="w-4 h-4" /> Generate guide</>}
              </Button>
            )}
          </div>
        </div>
      </Card>

      {displayGuide && (
        <Card>
          <div className="prose prose-sm max-w-none text-charcoal-700">
            <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-charcoal-700 bg-transparent p-0 m-0 border-0">
              {displayGuide}
            </pre>
          </div>
        </Card>
      )}

      {!displayGuide && dog && (
        <Card className="text-center py-10">
          <Sparkles className="w-10 h-10 text-charcoal-200 mx-auto mb-3" />
          <h3 className="font-semibold text-charcoal-700 mb-1">No guide yet</h3>
          <p className="text-sm text-charcoal-400 mb-4">Click Generate to create a personalized sitter guide for {dog.name}</p>
        </Card>
      )}
    </div>
  )
}
